version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto21

  build:
    commands:
      - cd book-management-api
      - chmod +x gradlew
      - ./gradlew bootJar -x test

  post_build:
    commands:
      - cd ..
      - mkdir -p deploy-backend
      - cp book-management-api/build/libs/*-SNAPSHOT.jar deploy-backend/note-app.jar
      - cp book-management-api/Procfile deploy-backend/
      - '[ -d book-management-api/.ebextensions ] && cp -r book-management-api/.ebextensions deploy-backend/ || true'
      - ls -la deploy-backend/

artifacts:
  files:
    - '**/*'
  base-directory: deploy-backend
  discard-paths: no